covid_stretch/dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_dashboard, name='dashboard'),

    path('password/', views.change_password, name='change_password'),
    path('account/', views.update_account_basics, name='update_account_basics'),
    path('profile/', views.update_profile, name='update_profile'),

    path('researcher/', views.researcher_dashboard, name='researcher_dashboard'),
    path('researcher/export_people/', views.export_people, name='export_people'),
    path('researcher/export_moods/', views.export_moods, name='export_moods'),
    path('researcher/export_userlog/', views.export_userlog, name='export_userlog'),

    path('linkworkers/', views.linkworker_list, name='linkworker_list'),
    path('linkworker/', views.linkworker_details, name='linkworker_mydetails'),
    path('linkworker/<int:pk>/details/', views.linkworker_details, name='linkworker_details'),
    # path('linkworker/<int:pk>/export/', views.linkworker_export, name='linkworker_export'),

    path('pacs/', views.pac_list, name='pac_list'),
    path('pac/', views.pac_details, name='pac_mydetails'),
    path('pac/<int:pk>/details/', views.pac_details, name='pac_details'),
    path('pac/<int:pk>/timeline/', views.pac_timeline, name='pac_timeline'),
    path('pac/<int:pk>/export/', views.pac_export, name='pac_export'),
    path('pac/<int:pk>/export/circles/', views.pac_export_circles, name='pac_export_circles'),
    path('pac/<int:pk>/export/userlog/', views.pac_export_userlog, name='pac_export_userlog'),
    path('pac/<int:pk>/moodspider_chart/', views.moodspider_chart, name='moodspider-chart'),
    path('pac/<int:pk>/moodtimeline_chart/', views.moodtimeline_chart, name='moodtimeline-chart'),
    path('pac/<int:pk>/moodsparkline_chart/', views.moodsparkline_chart, name='moodsparkline_chart'),
    # path('membership_chart/', views.membership_chart, name='membership-chart'),
    # path('export/', views.export),
]

covid_stretch/user_profile/models.py
import random

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from multiselectfield import MultiSelectField
from phone_field import PhoneField

HOW_OFTEN_EXPECTED_INTERACTION_CHOICES = (
    (1, "Daily"),
    (2, "Weekly"),
    (3, "Fortnightly"),
    (4, "Monthly"),
    (5, "Yearly")
)

class UserProfile(models.Model):
    PERSON_AT_CENTRE = "PAC"
    LINKWORKER = "LNK"
    SUPPORTER = "SUP"
    ADMIN = "ADM"
    NO_ROLE = "NOR"
    
    ROLE_CHOICES = (
        (PERSON_AT_CENTRE, "pac"),
        (LINKWORKER, "linkworker"),
        (SUPPORTER, "supporter"),
        (ADMIN, "admin"),
        )
    
    GENDER_CHOICES = (
        ("WOM", "Woman"),
        ("MAN", "Man"),
        ("NBIN", "Non-binary"),
        ("PNTD", "Prefer not to disclose"),
        ("PTSD", "Prefer to self describe")
        )
    
    ETHNIC_CHOICES = (
        ("WHTE", "White"),
        ("MXED", "Mixed/Multiple ethnic groups"),
        ("ASIN", "Asian/Asian British"),
        ("BLCK", "Black/African/Caribbean/Black British"),
        ("CHIN", "Chinese"),
        ("ARAB", "Arab"),
        ("OTHR", "Other")
        )
    
    EDUCATION_CHOICES = (
        ("NONE", "No qualifications"),
        ("GCE1", "1-4 GCSEs, Scottish Standard Grade"),
        ("GCE5", "5 or more GCSEs, Scottish Higher, Scottish Advanced Higher"),
        ("APRT", "Apprenticeship"),
        ("ALEV", "2 or more A-levels, HNC, HND, SVQ level 4"),
        ("DEGR", "First or higher degree"),
        ("OTHR", "Other vocational / work related qualifications")
        )
    
    # https://meassociation.org.uk/2016/05/the-mea-disability-rating-scale-2016/
    DISABILITY_CHOICES = (
        ("NONE", "No disability"),
        ("MILD", "Mild to moderate disability"),
        ("MODD", "Moderate disability"),
        ("SVDS", "Severe disability"),
        ("VERY", "Very severe disability")
        )
    
    # ONS data
    HEALTH_CHOICES = (
        ("0", "No health problems"),
        ("1", "Arms or hands"),
        ("2", "Back or neck"),
        ("3", "Difficulty in seeing"),
        ("4", "Difficulty in hearing"),
        ("5", "Speech impediment"),
        ("6", "Skin conditions, allergies"),
        ("7", "Chest, breathing problems"),
        ("8", "Heart, blood, blood pressure, circulation"),
        ("9", "Stomach, liver, kidney, digestion"),
        ("10", "Diabetes"),
        ("11", "Depression, bad nerves"),
        ("12", "Epilepsy"),
        ("13", "Learning difficulties"),
        ("14", "Mental illness, phobia, panics"),
        ("15", "Progressive illness n.e.c."),
        ("16", "Other problems, disabilities")
        )
    
    # https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/bulletins/populationestimatesbymaritalstatusandlivingarrangements/2002to2016
    MARITAL_CHOICES = (
        ("SING", "Single, never married or civil partnered"),
        ("MARR",
         "Married, including separated (this category includes those in both opposite-sex and same-sex marriages)"),
        ("CIVL", "Civil partnered, including separated "),
        ("DIVD", "Divorced, including legally dissolved civil partners"),
        ("WIDO", "Widowed, including surviving civil partners")
        )

    SOCIAL_GROUPS_CHOICES = (
        ("FAML", "Family"),
        ("FRND", "Friends"),
        ("SOCL", "Social club"),
        ("SPRT", "Sport"),
        ("PROF", "Professional"),
        ("VOLN", "Voluntary"),
        ("LEAR", "Learning"),
        ("NBOR", "Neighbourhood"),
        ("FATH", "Faith"),
        ("POLI", "Political"),
        ("OTHR", "Other group")
    )

    LIKES_DISLIKES_CHOICES = (
        ("TV", "TV"),
        ("EXER", "Exercise"),
        ("ART", "Arts & Crafts"),
        ("COOK", "Cooking"),
        ("READ", "Reading"),
        ("SOC", "Socialising"),
        ("GARD", "Gardening"),
        ("COMP", "Computer"),
        ("HYG", "Hygiene"),
        ("CLEN", "Cleaning"),
        ("VOL", "Volunteering"),
        ("MUS", "Music"),
    )

    BOND_CHOICES = ( #zip(range(0, 8), range(0, 8))
        (None, "No answer"),
        (1, "1 - Very distant"),
        (2, "2 - Somewhat distant"),
        (3, "3 - Slightly distant"),
        (4, "4 - Neither close nor distant"),
        (5, "5 - Slightly close"),
        (6, "6 - Somewhat close"),
        (7, "7 - Very close"),

    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_on = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(default=timezone.now)
    role = models.CharField(max_length=3, choices=ROLE_CHOICES, default=SUPPORTER, blank=True, null=True)
    phone = PhoneField(help_text="Contact phone number", blank=True, null=True)
    image = models.ImageField(default="1.jpg", blank=True, null=True)
    date_of_birth = models.DateField(default=timezone.now, blank=True, null=True)
    gender = models.CharField(max_length=4, choices=GENDER_CHOICES, default="PTSD")
    ethnicity = models.CharField(max_length=4, choices=ETHNIC_CHOICES, default="OTHR")
    education = models.CharField(max_length=4, choices=EDUCATION_CHOICES, default="NONE")
    disability = models.CharField(max_length=4, choices=DISABILITY_CHOICES, default="NONE")
    marital_status = models.CharField(max_length=4, choices=MARITAL_CHOICES, default="SING")
    smoking = models.BooleanField(default=False)
    alcohol_units_per_week = models.PositiveIntegerField(choices=zip(range(0, 251), range(0, 251)),default=0)
    # https://pypi.org/project/django-multipleselectfield/
    health_conditions = MultiSelectField(choices=HEALTH_CHOICES, max_choices=15, max_length=3, default="0")
    things_liked = models.CharField(max_length=4, choices=LIKES_DISLIKES_CHOICES, default="")
    things_disliked = models.CharField(max_length=4, choices=LIKES_DISLIKES_CHOICES, default="")
    family_has = models.BooleanField(default=False)
    family_bond = models.IntegerField(choices=BOND_CHOICES, null=True, blank=True)
    community_bond = models.IntegerField(choices=BOND_CHOICES, null=True, blank=True)
    social_groups = models.CharField(max_length=4, choices=SOCIAL_GROUPS_CHOICES, blank=True, null=True)
    social_group_other = models.CharField(max_length=32, blank=True, null=True)
    social_bond = models.IntegerField(choices=BOND_CHOICES, null=True, blank=True)
    link_worker_has = models.BooleanField(default=False)
    link_worker_bond = models.IntegerField(choices=BOND_CHOICES, null=True, blank=True)
    # TODO: Privacy fields to follow
    
    def get_full_name(self):
        fn = self.user.first_name + " " + self.user.last_name
        return fn
    
    def is_linkworker(self):
        ret = False
        if self.role == self.LINKWORKER:
            ret = True
        return ret
    
    def is_supporter(self):
        ret = False
        if self.role == self.SUPPORTER:
            ret = True
        return ret
    
    def is_pac(self):
        ret = False
        if self.role == self.PERSON_AT_CENTRE:
            ret = True
        return ret
    
    def get_user_details(self):
        return "Name: {} UserName: {}".format(self.user.get_full_name(), self.user.username)
    
    def get_id(self):
        return self.user.id
    
    def __str__(self):
        return self.get_user_details()
    
    def randomise_personal_details(self):
        self.gender = random.choice(self.GENDER_CHOICES)[0]
        self.ethnicity = random.choice(self.ETHNIC_CHOICES)[0]
        self.education = random.choice(self.EDUCATION_CHOICES)[0]
        self.disability = random.choice(self.DISABILITY_CHOICES)[0]
        self.marital_status = random.choice(self.MARITAL_CHOICES)[0]
        self.smoking = random.choice([True, False])
        self.alcohol_units_per_week = random.randrange(30)
        self.health_conditions = random.choice(self.HEALTH_CHOICES)[0]
        # choices above this line were commented out until multi-user-pastimes were added
        self.things_liked = random.choice(self.LIKES_DISLIKES_CHOICES)[0]
        self.things_disliked = random.choice(self.LIKES_DISLIKES_CHOICES)[0]
        self.family_has = random.choice([True, False])
        self.family_bond = random.randrange(7)
        self.community_bond = random.randrange(7)
        self.social_groups = random.choice(self.SOCIAL_GROUPS_CHOICES)[0]
        self.social_group_other = random.choice(self.SOCIAL_GROUPS_CHOICES)[0]
        self.social_bond = random.randrange(7)
        self.link_worker_has = random.choice([True, False])
        self.link_worker_bond = random.randrange(7)


class Supporter(models.Model):
    SOCIAL_GROUPS_CHOICES = (
        ("FAML", "Family"),
        ("FRND", "Friends"),
        ("SOCL", "Social club"),
        ("SPRT", "Sport"),
        ("PROF", "Professional"),
        ("VOLN", "Voluntary"),
        ("LEAR", "Learning"),
        ("NBOR", "Neighbourhood"),
        ("FATH", "Faith"),
        ("POLI", "Political"),
        ("OTHR", "Other group")
    )

    user_profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE, related_name="supporters")
    group = models.CharField(max_length=4, choices=SOCIAL_GROUPS_CHOICES, blank=True, null=True)
    how_often_expected_interaction = models.IntegerField(choices=HOW_OFTEN_EXPECTED_INTERACTION_CHOICES, null=True, blank=True)
    user_profile.role = UserProfile.SUPPORTER


class Person_at_centre(models.Model):
    MOOD_STATUS_NEW = "NEW"  # this is a new account - no mood yet
    MOOD_STATUS_NORMAL = "NRM"  # Normal mode - moods are regularly updated
    MOOD_STATUS_DORMANT = "DRM"  # Dormant - client not responding
    MOOD_STATUS_REQUIRES_UPDATE = "UPD"  # Person_at_centre needs to add a new mood reading
    
    MOOD_STATUS_CHOICES = (
        (MOOD_STATUS_NEW, "new"),
        (MOOD_STATUS_NORMAL, "normal"),
        (MOOD_STATUS_DORMANT, "dormant"),
        (MOOD_STATUS_REQUIRES_UPDATE, "update"),
        )
    

covid_stretch/templates/base.html
<!-- templates/base.html -->
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- reference your installed Font Awesome Free package's files here -->
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- reference your installed Font Awesome Pro package's files here -->
    <link href="{% static 'fontawesomepro/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <title>SERVICE</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'cropped-service_logo2_icon-32x32.png' %}" sizes="32x32"/>
    <link rel="icon" href="{% static 'cropped-service_logo2_icon-32x32.png' %}" sizes="32x32"/>
    <link rel="icon" href="{% static 'cropped-service_logo2_icon-192x192.png' %}" sizes="192x192"/>
    <link rel="apple-touch-icon" href="{% static 'cropped-service_logo2_icon-180x180.png' %}"/>
    <meta name="msapplication-TileImage" content="{% static 'cropped-service_logo2_icon-270x270.png' %}"/>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>

    {% block header %}
    {% endblock %}

    <style>

        body.servicecontent {
            background: rgb(0,123,255);
            background: linear-gradient(90deg,
                rgba(0,123,255,0.33) 0%,
                rgba(0,123,255,0.1) 33%,
                rgba(0,123,255,0.1) 67%,
                rgba(0,123,255,0.33) 100%
            );
        }

        a:hover {
            text-decoration: none;
        }

        nav.topservicebar {
            background: rgb(0,123,255);
            background: linear-gradient(0deg, rgba(0,123,255,0) 0%, rgba(0,123,255,1) 25%, rgba(0,123,255,1) 100%);
        }
        nav.bottomservicebar {
            background: rgb(0,123,255);
            background: linear-gradient(180deg, rgba(0,123,255,0) 0%, rgba(0,123,255,1) 25%, rgba(0,123,255,1) 100%) !IMPORTANT;
        }

        label:not(.form-check-label),
        label[for="id_smoking"],
        label[for="id_family_has"],
        label[for="id_link_worker_has"]
        {
            font-weight: 700;
        }

        /*#id_family_bond,*/
        /*#id_link_worker_bond,*/
        /*#id_community_bond*/
        /*{*/
        /*    width: 4em;*/
        /*    display: inline-block;*/
        /*}*/

        #id_date_of_birth_day {
            display: inline-block;
            width: 4em;
        }
        #id_date_of_birth_month {
            display: inline-block;
            width: 10em;
        }
        #id_date_of_birth_year {
            display: inline-block;
            width: 5em;
        }
    </style>

</head>

<body class="servicecontent">
<nav class="navbar navbar-expand-lg navbar-light topservicebar pt-0"> <!-- bg-primary -->
    {% if includenavigation %}
    <a class="navbar-brand text-light mr-1" href="{% url 'dashboard' %}">
        SERVICE
    </a>
    {% else %}
    <a class="navbar-brand text-light mr-1" href="#">
        SERVICE
    </a>
    {% endif %}
    <span class="badge badge-warning mr-3">&beta;</span>&nbsp;

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            {% if includenavigation %}
            <li class="nav-item">
                <a class="nav-link" href="/dashboard/" target="_new">Research&nbsp;dashboard</a>
            </li>
            <li class="nav-item">
<!--                <a class="nav-link" href="/dashboard/">Linkworker <span class="sr-only">(current)</span></a>-->
                <a class="nav-link" href="/dashboard/linkworkers">Linkworker&nbsp;list</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/dashboard/pacs" target="_new">People&nbsp;at&nbsp;Centre</a>
            </li>
            {% endif %}
        </ul>

<!--            <li class="nav-item dropdown">-->
<!--                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink1" role="button"-->
<!--                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--                    Resources&hellip;-->
<!--                </a>-->
<!--                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">-->
<!--                    <a class="dropdown-item" href="/admin/">System Management</a>-->
<!--                    <h6 class="dropdown-header">Technologies</h6>-->
<!--                    <a class="dropdown-item" href="https://www.python.org">Python</a>-->
<!--                    <a class="dropdown-item" href="https://www.djangoproject.com">Django</a>-->
<!--                    <a class="dropdown-item" href="https://getbootstrap.com/docs/4.3/getting-started/introduction/">Bootstrap</a>-->
<!--                </div>-->
<!--            </li>-->

        {% if user.is_authenticated %}
        <ul class="navbar-nav justify-content-end" style="width: 100%;">
            {% if isAdmin %}
                <a class="btn-sm btn-warning">Admin mode</a>
            {% endif %}

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle  text-light" href="#" id="navbarDropdownMenuLink2" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle"></i> {{user.first_name}} {{user.last_name}} ({{user.username}})&hellip;
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink2">
                    <a class="dropdown-item" href="/accounts/logout/">Log out</a>
                    <div class="dropdown-divider"></div>
                    <h6 class="dropdown-header">Account options</h6>
                    <a class="dropdown-item" href="/dashboard/password/">Change your password</a>
                    <a class="dropdown-item" href="/dashboard/account/">Edit your account</a>
                    <a class="dropdown-item" href="/dashboard/profile/">Edit your profile</a>
                    <a class="dropdown-item" href="/accounts/password_reset/">Request a password reset</a>
                </div>
            </li>
            {% endif %}

        </ul>
    </div>

</nav>
<div class="container m-3">

    {% if messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <i class="fas fa-exclamation-triangle"></i>&nbsp;
        <strong>Attention</strong><br/>
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message|safe }}
            </li>
            {% endfor %}
        </ul>
        <button aria-label="Close" class="close" data-dismiss="alert" type="button">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}

    <h1>{% block title %}
    {% endblock %}</h1>

    {% block content %}
    {% endblock %}

</div>

<nav class="navbar navbar-expand-lg navbar-light bottomservicebar"> <!-- bg-primary -->
    <p class="text-light mb-0 mt-1">&copy; SERVICE /
        <a class="text-light" href="http://stem.open.ac.uk">STEM</a>
        /
        <a class="text-light" href="http://www.open.ac.uk">The Open University</a>
        2020-21
    </p>
</nav>

</body>
</html>